1 Step
brAnna2000/Current-Weather pull request #1
Opened 2022-01-14 11:25 UTC by brAnna2000

2022-01-14 11:30 UTC, brusnev-egor requested changes

2022-01-14 11:30 UTC, brusnev-egor commented on src/App.tsx
> +            <CitiesList />
?

2022-01-14 11:30 UTC, brusnev-egor commented on src/components/citiesList/index.tsx
> +import List from '@mui/material/List';
should be in another pr

2022-01-14 11:30 UTC, brusnev-egor commented on src/components/search/index.tsx
> +import { useState, useEffect } from 'react';
should be in another pr

2022-01-14 11:30 UTC, brusnev-egor commented on src/App.tsx
> +            <CitiesList />
should be in another pr

2022-01-14 11:30 UTC, brusnev-egor commented on src/components/search/style.css
> +.searchBox {
should be in another pr

2022-01-14 11:30 UTC, brusnev-egor commented on src/components/weatherInfo/index.tsx
> +import List from '@mui/material/List';
should be in another pr

2022-01-14 11:30 UTC, brusnev-egor commented on package.json
> +        "@emotion/styled": "^11.6.0",
what is this and why do you need this?

2022-01-14 11:30 UTC, brusnev-egor commented on package.json
> +        "lint": "eslint src/**/*.js src/**/*.jsx",
lint for all files, not only js. Basically you will have typescript files in project, not only js one

2022-01-14 11:30 UTC, brusnev-egor commented on package.json
> +        "web-vitals": "^2.1.3"
remove `^` for all dependencies

2022-01-14 11:31 UTC, brusnev-egor reviewed
All commits should be meaningfull and in English

2022-01-17 14:03 UTC, yuliabarysenka commented on src/App.tsx
> +    return <div className="App">а</div>;
It will be better if you remove the 'a' letter in the div element, if you don't necessary it, of course.

2022-01-17 14:11 UTC, yuliabarysenka commented on package.json
> +        "eslint-plugin-prettier": "^4.0.0",
You can use a command (`npm config set save-prefix='`') to remove auto-prefixing, then you don't have to do it manually anymore.

2022-01-17 14:35 UTC, closed without merging