Initial setup
brAnna2000/Current-Weather pull request #2
Opened 2022-01-17 14:52 UTC by brAnna2000

2022-01-17 14:58 UTC, yuliabarysenka requested changes

2022-01-17 14:58 UTC, yuliabarysenka commented on src/App.tsx
> +    return <div className="App">а</div>;
It will be better if you remove the 'a' letter in the div element, if you don't necessary it, of course.

2022-01-17 14:58 UTC, yuliabarysenka commented on package.json
> +        "eslint-plugin-prettier": "^4.0.0",
You can use a command (npm config set save-prefix='') to remove auto-prefixing, then you don't have to do it manually anymore.

2022-01-19 10:39 UTC, MurphyDM approved these changes

2022-01-19 10:39 UTC, yuliabarysenka approved these changes

2022-01-19 10:47 UTC, kozlova-anzhelika approved these changes

2022-01-19 15:04 UTC, brusnev-egor approved these changes

2022-01-20 12:34 UTC, egor-brusnev approved these changes

2022-01-20 12:37 UTC, merged